# Generated by Django 5.1.4 on 2024-12-12 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(blank=True, max_length=30, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("familia", models.CharField(max_length=100)),
                ("largo", models.DecimalField(decimal_places=2, max_digits=5)),
                ("ancho", models.DecimalField(decimal_places=2, max_digits=5)),
                ("grosor", models.DecimalField(decimal_places=2, max_digits=5)),
                ("existencias", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="HistorialCambios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accion", models.CharField(max_length=50)),
                ("producto", models.CharField(max_length=100)),
                ("motivo", models.TextField(blank=True, null=True)),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
