# Generated by Django 5.1.4 on 2024-12-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controlinventario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="productos/"),
        ),
    ]
