# Generated by Django 5.1.4 on 2024-12-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controlinventario", "0002_producto_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="imagen",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
